---
kind: pipeline
type: kubernetes
name: build
service_account_name: kube-deployer
steps:
- name: image
  image: images.home.mtaylor.io/drone-kaniko:latest
  settings:
    repo: images.home.mtaylor.io/jupyter
    auto_tag: true
    enable_cache: true
    username: anonymous
    password: anonymous
    registry: images.home.mtaylor.io
- name: deploy
  image: images.home.mtaylor.io/deployer:latest
  commands:
  - kubectl apply -k deploy/staging
  when:
    ref:
    - refs/tags/*
- name: release
  image: images.home.mtaylor.io/deployer:latest
  commands:
  - set -u
  - git fetch origin 'refs/tags/*:refs/tags/*'
  - git fetch origin $${DRONE_BRANCH}
  - export tag=$(get-release-tag)
  - (cd deploy/base && kustomize edit set image images.home.mtaylor.io/jupyter:$${tag})
  - git add deploy/base/kustomization.yml
  - git diff --staged
  - git commit -m "Release $${tag}"
  - git tag $${tag}
  - git push origin $${tag}
  when:
    branch:
    - main
trigger:
  event:
  - push
  - tag
  - custom
